[CmdletBinding()]
param([string]$Root='C:\gokuai',[ValidateRange(4096,65536)][int]$ContextSize=16384,[ValidateSet('4','6','8','8,4','fp8','nvfp4')][string]$CacheQuant='8')
Set-StrictMode -Version Latest;$ErrorActionPreference='Stop'
$envFile=Join-Path $Root 'runtime\mia-kit\.env';$py=Join-Path $Root 'runtime\mia-kit\.venv\Scripts\python.exe';$bench=Join-Path $Root 'scripts\benchmark_stage2.py';$reset=Join-Path $Root 'Reset-GokuBackend.ps1';$start=Join-Path $Root 'Start-GokuBackend.ps1'
$candidateFile=Join-Path $Root 'models\Candidates\candidate-manifest.json';$candidates=Get-Content $candidateFile -Raw|ConvertFrom-Json
$plan=@(
 [pscustomobject]@{key='current_fast';label='Current Qwen3-Coder 30B-A3B 4bpw';path=Join-Path $Root 'models\EXL3\qwen3-coder-30b-a3b-exl3-4bpw';draft='none';draftPath='none'},
 [pscustomobject]@{key='current_heavy_mtp';label='Current Qwen3.8-27B 3.5bpw MTP';path=Join-Path $Root 'models\EXL3\qwen3.8-27b-exl3-3.5bpw';draft='mtp';draftPath='none'},
 [pscustomobject]@{key='current_heavy_dflash';label='Current Qwen3.8-27B 3.5bpw DFlash2';path=Join-Path $Root 'models\EXL3\qwen3.8-27b-exl3-3.5bpw';draft='dflash2';draftPath=Join-Path $Root 'models\EXL3\qwen3.8-27b-dflash2-exl3-5bpw'}
)
foreach($c in $candidates){$plan+=,[pscustomobject]@{key=$c.key;label="$($c.key) candidate";path=$c.path;draft='none';draftPath='none'}}
$stamp=Get-Date -Format 'yyyyMMdd_HHmmss';$dir=Join-Path $Root "benchmarks\java-repair-stage2-$stamp";$parts=Join-Path $dir 'parts';New-Item $parts -ItemType Directory -Force|Out-Null;$final=Join-Path $dir 'stage2-benchmark.json';$saved=[IO.File]::ReadAllText($envFile);$utf8=New-Object Text.UTF8Encoding $false
function Set-Key($lines,$key,$value){$found=$false;$o=foreach($line in $lines){if($line-match ('^\s*'+[regex]::Escape($key)+'\s*=')){$found=$true;"$key=$value"}else{$line}};if(-not$found){$o+="$key=$value"};,@($o)}
function Configure($p){$l=Get-Content $envFile;$l=Set-Key $l MODEL_DIR ($p.path-replace'\\','/');$l=Set-Key $l DRAFT $p.draft;$l=Set-Key $l DRAFT_DIR ($p.draftPath-replace'\\','/');$l=Set-Key $l CONTEXT_SIZE "$ContextSize";$l=Set-Key $l CACHE_QUANT $CacheQuant;[IO.File]::WriteAllLines($envFile,$l,$utf8)}
$result=[ordered]@{schema='goku-java-repair-stage2-all-v1';created=(Get-Date).ToString('o');context_size=$ContextSize;cache_quant=$CacheQuant;models=[ordered]@{}}
try{foreach($p in $plan){Write-Host "`n=== Stage 2: $($p.key) ===" -ForegroundColor Cyan;$e=[ordered]@{label=$p.label;path=$p.path;draft=$p.draft;status='pending';started=(Get-Date).ToString('o')};$result.models[$p.key]=$e;try{if(-not(Test-Path $p.path)){throw "Missing model: $($p.path)"};&$reset -Root $Root -TargetUsedMiB 2500 -MaxWaitSeconds 120;Configure $p;&$start -Root $Root -ForceRestart;$part=Join-Path $parts "$($p.key).json";&$py $bench --output $part --report-as $p.key --worker-label $p.label;if($LASTEXITCODE-ne0){throw "benchmark exit $LASTEXITCODE"};$b=(Get-Content $part -Raw|ConvertFrom-Json).models.PSObject.Properties[$p.key].Value;$e.status='passed';$e.quality_score=$b.quality_score;$e.success_rate=$b.success_rate;$e.mean_seconds=$b.mean_seconds;$e.result_file=$part}catch{$e.status='failed';$e.error=$_.Exception.Message;$log=Join-Path $Root 'logs\backend\mia-server.stderr.log';if(Test-Path $log){$e.backend_error_tail=@(Get-Content $log -Tail 25)};Write-Warning "$($p.key) failed: $($_.Exception.Message)"}finally{&$reset -Root $Root -TargetUsedMiB 2500 -MaxWaitSeconds 120;$e.completed=(Get-Date).ToString('o');$result|ConvertTo-Json -Depth 16|Set-Content $final -Encoding UTF8}}}finally{[IO.File]::WriteAllText($envFile,$saved,$utf8);&$reset -Root $Root -TargetUsedMiB 2500 -MaxWaitSeconds 120}
$passed=@($result.models.Values|Where-Object{$_.status-eq'passed'}).Count;$failed=@($result.models.Values|Where-Object{$_.status-eq'failed'}).Count;$result.summary=[ordered]@{passed=$passed;failed=$failed;total=$plan.Count};$result|ConvertTo-Json -Depth 16|Set-Content $final -Encoding UTF8;Write-Host "Stage 2 complete: $passed passed, $failed failed. $final" -ForegroundColor $(if($failed){'Yellow'}else{'Green'});if($failed){exit 1}
